[package]
name = "z-wallet-core"
authors = ["zeno-studio <zenostudio@proton.me>"]
version = "0.1.0"
edition = "2024"
description = "Crypto wallet core"
keywords = ["wallet", "ethereum", "core"]
repository = "https://github.com/zeno-studio/z-wallet-core"
homepage = "https://zeno.pw"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

alloy-signer-local = { version = "1.0.32", features = ["mnemonic"] }
alloy-primitives = "1.3.1"
alloy-signer = "1.0.32"
alloy-network = "1.0.33"
alloy-eips = { version = "1.0.36", features = ["serde"] }
alloy-consensus = "1.0.36"
argon2 = "0.5.3"
bip39 = { version = "1.1.0", features = [ "zeroize"] }
chacha20poly1305 = "0.10.1"
serde = { version = "1.0.225"}
serde_json = { version = "1.0.145", default-features = false }
js-sys = "0.3.80"
zeroize = "1.8.1"
hex = "0.4.3"
getrandom = "0.3.4"
thiserror = "2.0.17"
